### ISSUE TITLE
Step mode?

### ISSUE THREAD

**Issue by basille** [mablab/rpostgisLT#4]
Is there currently any visible difference with Step mode on or off? If I click on a given step, then enable step mode, and click on the same step again, I get the exact same information.

Also, it would be nice to have step information in step mode (x, y, dx, dy, dist, angles, etc.) and possibly infolocs too.

**Comment by balazsdukai** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [issue#4](https://trello.com/c/yNbcqRmW/58-issue4)

**Comment by balazsdukai** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Information overlay](https://trello.com/c/0Zis0vMq/33-information-overlay)

**Comment by balazsdukai** [comment]
Re-render trajectory on Step mode switch implemented in 7c667302340072e75e38007c4b11725133f0f96b

**Comment by balazsdukai** [comment]
Chose the approach of materializing separate views for steps and burst with the `createShinyStepsView(conn, schema, pgtraj)` and `createShinyBurstsView(conn, schema)` functions 5a8e86ca740d53feadb1d8f340615c7d638214bc It means that is not possible to create the shiny-views if a pgtraj is not projected in the schema. (currently checks only the first pgtraj, but will check all). This is because createShinyBurstsViews() needs all pgtrajes in the schema.
